### PR TITLE
Roy/event dispatcher

### PR DESCRIPTION
**Pull request by Hidinkyu**

### CODE REVIEW

**Comment by WVAviator** [comment]
Did you want me and Maria to merge our code first so that yours works without errors?

**Comment by Hidinkyu** [comment]
> Did you want me and Maria to merge our code first so that yours works without errors?

Yes, please

**Comment by WVAviator** [comment]
Can you pull and merge in the latest "development"?
Also both mine and Maria's code is merged into dev now so you should be able to get the type and the webhook instance all working together with your code.

**Comment by WVAviator** [comment]
Also can you remove the package-lock.json since we're using yarn

**Comment by Hidinkyu** [comment]
Currently absent from home, will do that ASAP

**Review by kmarrow1 — APPROVED** [review]

**Review by WVAviator — APPROVED** [review]

**Pull request merged**
